app = "salary-score"
primary_region = "iad"

[deploy]
#release_command = "npx prisma migrate deploy"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 1
max_machines_running = 1
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"
memory_mb = 512